behat.yml.dist, composer.json, tests/features/av-portal-video.feature, tests/features/document.feature, tests/features/image.feature, tests/features/remote-video.feature
=> OPENEUROPA-1522: Make sure we don't use Drupal paths in Behat scenarios.

.drone.yml, README.md, behat.yml.dist, docker-compose.yml, modules/oe_media_avportal/config/install/core.entity_form_display.media.av_portal_photo.default.yml, modules/oe_media_avportal/config/install/core.entity_view_display.media.av_portal_photo.default.yml, modules/oe_media_avportal/config/install/field.field.media.av_portal_photo.oe_media_avportal_photo.yml, modules/oe_media_avportal/config/install/field.storage.media.oe_media_avportal_photo.yml, modules/oe_media_avportal/config/install/media.type.av_portal_photo.yml, modules/oe_media_avportal/config/schema/oe_media_avportal.schema.yml, modules/oe_media_demo/config/install/core.entity_form_display.node.oe_media_demo.default.yml, modules/oe_media_demo/config/install/core.entity_view_display.node.oe_media_demo.default.yml, modules/oe_media_demo/config/install/entity_browser.browser.media_entity_browser.yml, modules/oe_media_demo/config/install/field.field.node.oe_media_demo.field_oe_demo_av_portal_photo.yml, modules/oe_media_demo/config/install/field.storage.node.field_oe_demo_av_portal_photo.yml, modules/oe_media_demo/config/install/views.view.media_entity_browser.yml, tests/Behat/AvPortalContext.php, tests/features/av-portal-photo.feature, tests/features/av-portal-video.feature
=> OPENEUROPA-1557: Photography media type

modules/oe_media_avportal/config/install/views.view.av_portal_entity_browsers.yml, modules/oe_media_avportal/oe_media_avportal.install, modules/oe_media_avportal/oe_media_avportal.views.inc, modules/oe_media_avportal/src/Plugin/views/field/AvPortalThumbnail.php, modules/oe_media_avportal/src/Plugin/views/filter/AvPortalTypeSearch.php, modules/oe_media_avportal/tests/Kernel/AvPortalViewsTest.php
* View with 3 displays (not used by any entity browser)
* Minor bug fixe
* Thumbnail improvement
=> OPENEUROPA-1585: OE Media should ship with an AV Portal entity browser view

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1669: Update change log for release 0.3.0.

CHANGELOG.md
Update change log for release 0.4.0.
- Changed: Change log file.
=> OPENEUROPA-1766: Update change log for release 0.4.0.

.drone.yml
Update drone file with latest best practice.
- Changed: .drone.yml file.
=> OPENEUROPA-1766: Update container on drone.

composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1864: Changed media_avportal dependency.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1864: Updated changelog.md.

behat.yml.dist, oe_media.install, tests/Behat/DrupalContext.php, tests/features/document.feature, tests/features/image.feature, tests/features/remote-video.feature
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1898: Revert value of standalone url option in oe_media.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-0000: Updated changelog.

CHANGELOG.md, composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Update CHANGELOG.md for release 1.0.0.

composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-0000: Bumping media_avportal version.

CHANGELOG.md, composer.json, modules/oe_media_avportal/tests/Kernel/AvPortalViewsTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1766: Prepare Release 1.2.0.

oe_media.install
This will go into EWCMS. We can't force others to update their AVportal items.
=> Revert "OPENEUROPA-2662: Update previously imported avportal medias."

.drone.yml, composer.json, docker-compose.yml
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2940: PHP 7.3. - Update OE Media component.

tests/Behat/MediaContext.php
Add createMediaRemoteVideo to MediaContext.
- Added: method createMediaRemoteVideo for testing remote media
=> EWPP-32: Add createMediaRemoteVideo to MediaContext.

CHANGELOG.md
Update changelog for 1.10.0
- Added:
- Changed: Update changelog for 1.10.0
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.10.0

README.md, behat.yml.dist, composer.json, modules/oe_media_demo/config/install/core.entity_form_display.node.oe_media_demo.default.yml, modules/oe_media_demo/config/install/core.entity_view_display.node.oe_media_demo.default.yml, modules/oe_media_demo/config/install/field.field.node.oe_media_demo.field_oe_demo_iframe.yml, modules/oe_media_demo/config/install/field.storage.node.field_oe_demo_iframe.yml, modules/oe_media_demo/oe_media_demo.info.yml, modules/oe_media_iframe/config/install/core.entity_form_display.media.iframe.default.yml, modules/oe_media_iframe/config/install/core.entity_view_display.media.iframe.default.yml, modules/oe_media_iframe/config/install/field.field.media.iframe.oe_media_iframe.yml, modules/oe_media_iframe/config/install/field.field.media.iframe.oe_media_iframe_ratio.yml, modules/oe_media_iframe/config/install/field.field.media.iframe.oe_media_iframe_thumbnail.yml, modules/oe_media_iframe/config/install/media.type.iframe.yml, modules/oe_media_iframe/oe_media_iframe.info.yml, tests/Behat/DrupalContext.php, tests/features/iframe.feature
Added new media type "Iframe".
=> EWPP-582: Create the Iframe media type.

modules/oe_media_iframe/config/post_updates/00004_create_media_iframe/media.type.iframe.yml, modules/oe_media_iframe/config/post_updates/00005_create_fields/field.field.media.iframe.oe_media_iframe.yml, modules/oe_media_iframe/config/post_updates/00005_create_fields/field.field.media.iframe.oe_media_iframe_ratio.yml, modules/oe_media_iframe/config/post_updates/00005_create_fields/field.field.media.iframe.oe_media_iframe_thumbnail.yml, modules/oe_media_iframe/config/post_updates/00006_create_displays/core.entity_form_display.media.iframe.default.yml, modules/oe_media_iframe/config/post_updates/00006_create_displays/core.entity_view_display.media.iframe.default.yml, modules/oe_media_iframe/oe_media_iframe.post_update.php
Update path for oe_media_iframe
=> EWPP-582: Create Iframe media

composer.json, modules/oe_media_webtools/config/post_updates/00002_install_op_publication_list/core.entity_form_display.media.webtools_op_publication_list.default.yml, modules/oe_media_webtools/config/post_updates/00002_install_op_publication_list/core.entity_view_display.media.webtools_op_publication_list.default.yml, modules/oe_media_webtools/config/post_updates/00002_install_op_publication_list/field.field.media.webtools_op_publication_list.oe_media_webtools.yml, modules/oe_media_webtools/config/post_updates/00002_install_op_publication_list/media.type.webtools_op_publication_list.yml, modules/oe_media_webtools/oe_media_webtools.post_update.php, oe_media.module
Add update path to install OP Publication lists.
- Added: Add update path to install OP Publication lists.
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-419: Install OP publication list media type on update.

src/Plugin/EntityBrowser/Widget/MediaCreationForm.php, tests/FunctionalJavascript/MediaCreationFormWidgetTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-629: Prevent selection loss of media bundle.

src/Plugin/EntityBrowser/Widget/MediaCreationForm.php, tests/FunctionalJavascript/MediaCreationFormWidgetTest.php
Fix bug where selecting value none would trigger error.
- Changed: MediaCreationForm media_bundle config.
=> EWPP-629: Fix select none.

README.md, behat.yml.dist, composer.json, modules/oe_media_demo/config/install/core.entity_form_display.node.oe_media_demo.default.yml, modules/oe_media_demo/config/install/core.entity_view_display.node.oe_media_demo.default.yml, modules/oe_media_demo/config/install/field.field.node.oe_media_demo.field_oe_demo_iframe.yml, modules/oe_media_demo/config/install/field.storage.node.field_oe_demo_iframe.yml, modules/oe_media_demo/oe_media_demo.info.yml, modules/oe_media_iframe/config/install/core.entity_form_display.media.iframe.default.yml, modules/oe_media_iframe/config/install/core.entity_view_display.media.iframe.default.yml, modules/oe_media_iframe/config/install/field.field.media.iframe.oe_media_iframe.yml, modules/oe_media_iframe/config/install/field.field.media.iframe.oe_media_iframe_ratio.yml, modules/oe_media_iframe/config/install/field.field.media.iframe.oe_media_iframe_thumbnail.yml, modules/oe_media_iframe/config/install/media.type.iframe.yml, modules/oe_media_iframe/config/post_updates/00004_create_media_iframe/media.type.iframe.yml, modules/oe_media_iframe/config/post_updates/00005_create_fields/field.field.media.iframe.oe_media_iframe.yml, modules/oe_media_iframe/config/post_updates/00005_create_fields/field.field.media.iframe.oe_media_iframe_ratio.yml, modules/oe_media_iframe/config/post_updates/00005_create_fields/field.field.media.iframe.oe_media_iframe_thumbnail.yml, modules/oe_media_iframe/config/post_updates/00006_create_displays/core.entity_form_display.media.iframe.default.yml, modules/oe_media_iframe/config/post_updates/00006_create_displays/core.entity_view_display.media.iframe.default.yml, modules/oe_media_iframe/oe_media_iframe.info.yml, modules/oe_media_iframe/oe_media_iframe.post_update.php, tests/Behat/DrupalContext.php, tests/features/iframe.feature
=> EWPP-584: Media iframe

composer.json, modules/oe_media_embed/src/Form/MediaEmbedDialog.php, modules/oe_media_embed/tests/src/FunctionalJavascript/CKEditorIntegrationTest.php, tests/src/Behat/AvPortalContext.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-844: Update epic ewpp 844 javascript asset.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-0000: Prepare for 1.15.0 release.

CHANGELOG.md, composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.16.0.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.17.0.

src/Plugin/EntityBrowser/Widget/MediaCreationForm.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-2170: Adjust access checking in \Drupal\oe_media\Plugin\EntityBrowser\Widget\MediaCreationForm class.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.20.0.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.21.0.

oe_media.module, tests/src/Kernel/MediaImageTest.php
Same PR as #213 but to a release branch to make a patch release.
=> OEL-2150: Fix assumptions that all medias using image source are coming from oe_media.

composer.json, modules/oe_media_webtools/src/Plugin/Field/FieldWidget/OpPublicationListIdWidget.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-2775: Replace 'service' by 'utility' for opwidget.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.27.0.

.drone.yml, tests/src/FunctionalJavascript/MediaCreationFormWidgetTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OEL-3034: Update to Drupal 10.3

modules/oe_media_iframe/tests/src/Kernel/OeMediaIframeFormatTest.php, modules/oe_media_iframe/tests/src/Unit/FilterIframeTagTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OEL-3034: Drop support for core 10.1.
